### ISSUE TITLE
Can't create repo

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-community/bosh-gen#39]
I want to create simple release consisted of apache job + apache package. But see this when I try to init release:

```
$ bosh-gen new apache                                                            
      create
Auto-detected infrastructure API credentials at ~/.fog (override with $FOG)
/Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection/auto_detection_fog.rb:56:in `auto_detection_choices': undefined method `inject' for false:FalseClass (NoMethodError)
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection.rb:41:in `block in aggregated_detector_choices'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection.rb:39:in `each'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection.rb:39:in `inject'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection.rb:39:in `aggregated_detector_choices'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/auto_detection.rb:18:in `perform'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/provider.rb:57:in `auto_detection'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/cyoi-0.11.2/lib/cyoi/cli/provider.rb:16:in `execute!'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/new_release_generator.rb:28:in `select_provider'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/bosh-gen-0.18.4/lib/bosh/gen/cli.rb:18:in `new'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/gems/bosh-gen-0.18.4/bin/bosh-gen:7:in `<top (required)>'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/bin/bosh-gen:23:in `load'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/bin/bosh-gen:23:in `<main>'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/lexsys/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by drnic** [comment]
Sorry I never saw this error til now - did you ever resolve it? are you able to share a sanitized version of your `~/.fog` file?

**Comment by jhunt** [comment]
@lexsys27 is this still a problem?

**Comment by lexsys27** [comment]
I don't remember if I solved this issue or used workaround. Now it is definitely not a problem as it is outdated and can be closed.
