### ISSUE TITLE
Selecting vSphere as the target results in error

### ISSUE THREAD

**Issue by omearaj** [cloudfoundry-community/bosh-gen#76]
I'm using bosh-gen to create a bosh release and when I select vsphere as the platform I get the following stack strace. It works for AWS. 

```
/Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:22:in `setup_credentials': undefined local variable or method`h1' for #Cyoi::Cli::Providers::ProviderCliVsphere:0x007fa6e2907910 (NameError)
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:6:in `perform_and_return_attributes'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/cyoi-0.11.3/lib/cyoi/cli/provider.rb:18:in`execute!'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/bosh-gen-0.22.0/lib/bosh/gen/generators/new_release_generator.rb:28:in `select_provider'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/bosh-gen-0.22.0/lib/bosh/gen/cli.rb:18:in`new'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/bosh-gen-0.22.0/bin/bosh-gen:7:in `<top (required)>'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/bin/bosh-gen:23:in`load'
    from /Users/jomeara/.rbenv/versions/2.0.0-p645/bin/bosh-gen:23:in `<main>'
```

**Comment by SamuelMarks** [comment]
+1

**Comment by Freakin** [comment]
+1

**Comment by neilhwatson** [comment]
+1

**Comment by drnic** [comment]
Closing as boshrelease blobs now only support AWS (and I think GCP from some recent commits).
